batch_size: 128
epsilon: 0.8
epsilon_decrement: 1.0e-05
gamma: 0.7
learning_rate: 0.0001
num_agents: 10
num_columns: 13
num_epochs: 10000
num_rows: 13
replay_size: 1000
state_dimension: 65
sync_rate: 5
tau: 0.01
time_to_live: 150
